pdf:
	texi2pdf src/thesis.tex -o output/Scalable\ Approaches\ for\ Learning\ Word\ Representations.pdf

pdf-mostly-clean:
	texi2pdf src/thesis.tex -o output/Scalable\ Approaches\ for\ Learning\ Word\ Representations.pdf --mostly-clean

.PHONY:
	pdf pdf-mostly-clean
