pdf:
	texi2pdf sources/acl2017.tex -o output/Scalable\ Word\ Embeddings.pdf
pdf-mostly-clean:
	texi2pdf sources/acl2017.tex -o output/Scalable\ Word\ Embeddings.pdf --mostly-clean

.PHONY:
	pdf pdf-mostly-clean
